services:
  db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456kz
      POSTGRES_DB: habit_tracker
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: 123456kz
      DB_NAME: habit_tracker
    volumes:
      - ./db/migrations:/app/db/migrations
    restart: on-failure
    command: sh -c "sleep 10 && ./habit-tracker"

volumes:
  db_data:
